<template><div><h1 id="net-core-公众号登录功能" tabindex="-1"><a class="header-anchor" href="#net-core-公众号登录功能"><span>.Net Core 公众号登录功能</span></a></h1>
<blockquote>
<p>通过接入微信公众号,用户关注后,发送关键字生成一个验证码,用户填写验证码正确则登录成功 反之失败.
个人公众号如何实现一个简单的回复关键字登录
xml格式通讯,需要自己准备一个xml转化工具</p>
</blockquote>
<h3 id="流程" tabindex="-1"><a class="header-anchor" href="#流程"><span>流程</span></a></h3>
<blockquote>
<p>1.根据微信公众号文档,首先配置接口地址.
2.根据用户关注后回复验证码 为关键字,随机生成一串数字为验证码,发送给用户.
3.用户填写后,点击登录即完成登录功能.</p>
</blockquote>
<h3 id="_1-第一步-配置微信公众号后台接口地址" tabindex="-1"><a class="header-anchor" href="#_1-第一步-配置微信公众号后台接口地址"><span>1. 第一步：配置微信公众号后台接口地址</span></a></h3>
<p>在微信公众号后台配置接口地址，如下所示：
<img src="https://github.com/user-attachments/assets/99d82936-412e-4db8-b5c4-1147f246ef77" alt="微信公众号配置"></p>
<h3 id="_2-第二步-代码配置" tabindex="-1"><a class="header-anchor" href="#_2-第二步-代码配置"><span>2. 第二步：代码配置</span></a></h3>
<p>我们需要设置一个 GET 请求以响应微信的请求，以及一个 POST 请求来接收微信发送过来的 XML 数据。</p>
<blockquote>
<p>如上方图片所示,我们Url 为 Token  例如 api/xxx/Token 确保Url正确才能使用
本地开发调试需要用到内网穿透工具.</p>
</blockquote>
<h3 id="_3-api-接口层" tabindex="-1"><a class="header-anchor" href="#_3-api-接口层"><span>3. API 接口层</span></a></h3>
<details>
  <summary>API 接口层代码</summary>
<div class="language-csharp line-numbers-mode" data-highlighter="prismjs" data-ext="cs"><pre v-pre><code><span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>summary</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// 微信公众号配置 验证token</span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>summary</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>echostr<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>param</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>returns</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>returns</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token punctuation">[</span>AllowAnonymous<span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">[</span><span class="token attribute"><span class="token class-name">HttpGet</span><span class="token attribute-arguments"><span class="token punctuation">(</span><span class="token string">"Token"</span><span class="token punctuation">)</span></span></span><span class="token punctuation">]</span>  <span class="token comment">// 微信公众号后台配置的地址url</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token return-type class-name">IActionResult</span> <span class="token function">Token</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> echostr<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">Content</span><span class="token punctuation">(</span>echostr<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>summary</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// 微信公众号配置 接收 微信 xml body内容</span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>summary</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>signature<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>param</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>timestamp<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>param</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nonce<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>param</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>openid<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>param</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>returns</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>returns</span><span class="token punctuation">></span></span></span></span>
<span class="line"><span class="token punctuation">[</span>AllowAnonymous<span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">[</span><span class="token attribute"><span class="token class-name">HttpPost</span><span class="token attribute-arguments"><span class="token punctuation">(</span><span class="token string">"Token"</span><span class="token punctuation">)</span></span></span><span class="token punctuation">]</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token keyword">async</span> <span class="token return-type class-name">Task<span class="token punctuation">&lt;</span>IActionResult<span class="token punctuation">></span></span> <span class="token function">Token</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">string</span></span> signature<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> timestamp<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> nonce<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">string</span></span> openid<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">try</span></span>
<span class="line">    <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">using</span> <span class="token class-name">StreamReader<span class="token punctuation">?</span></span> reader <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">StreamReader</span><span class="token punctuation">(</span>Request<span class="token punctuation">.</span>Body<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> xmlStr <span class="token operator">=</span> <span class="token keyword">await</span> reader<span class="token punctuation">.</span><span class="token function">ReadToEndAsync</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Log the incoming request if needed</span></span>
<span class="line">        <span class="token comment">// Logger.Info(LoggerType.Login, $"WeChat Request: {xmlStr}", null, null);</span></span>
<span class="line"></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> request <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">WeChatRequest</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">            XmlData <span class="token operator">=</span> xmlStr<span class="token punctuation">,</span></span>
<span class="line">            Signature <span class="token operator">=</span> signature<span class="token punctuation">,</span></span>
<span class="line">            Timestamp <span class="token operator">=</span> timestamp<span class="token punctuation">,</span></span>
<span class="line">            Nonce <span class="token operator">=</span> nonce</span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> result <span class="token operator">=</span> <span class="token keyword">await</span> _messageHandle<span class="token punctuation">.</span><span class="token function">Handle</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">return</span> <span class="token function">Content</span><span class="token punctuation">(</span>result<span class="token punctuation">,</span> <span class="token string">"text/xml"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 注意为xml格式</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Exception</span> ex<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// Log the error</span></span>
<span class="line">        Logger<span class="token punctuation">.</span><span class="token function">Error</span><span class="token punctuation">(</span>LoggerType<span class="token punctuation">.</span>Login<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">$"WeChat API Error: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">ex<span class="token punctuation">.</span>Message</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">,</span> ex<span class="token punctuation">.</span>StackTrace<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token function">Content</span><span class="token punctuation">(</span><span class="token keyword">string</span><span class="token punctuation">.</span>Empty<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
<h3 id="_4-handle-接收微信-xml-格式" tabindex="-1"><a class="header-anchor" href="#_4-handle-接收微信-xml-格式"><span>4. Handle 接收微信 XML 格式</span></a></h3>
<details>
  <summary>处理 Handle 接收微信 XML 格式</summary>
<div class="language-csharp line-numbers-mode" data-highlighter="prismjs" data-ext="cs"><pre v-pre><code><span class="line"><span class="token keyword">public</span> <span class="token keyword">async</span> <span class="token return-type class-name">Task<span class="token punctuation">&lt;</span><span class="token keyword">string</span><span class="token punctuation">></span></span> <span class="token function">Handle</span><span class="token punctuation">(</span><span class="token class-name">WeChatRequest</span> request<span class="token punctuation">,</span> <span class="token class-name">CancellationToken</span> cancellationToken <span class="token operator">=</span> <span class="token keyword">default</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name"><span class="token keyword">var</span></span> dicData <span class="token operator">=</span> <span class="token function">XmlToDic</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span>XmlData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name"><span class="token keyword">var</span></span> msgType <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"MsgType"</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>msgType <span class="token operator">==</span> <span class="token string">"event"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">{</span></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> eventType <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"Event"</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>eventType <span class="token operator">==</span> <span class="token string">"subscribe"</span> <span class="token operator">||</span> eventType <span class="token operator">==</span> <span class="token string">"unsubscribe"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">            <span class="token comment">// 关注或取消关注事件</span></span>
<span class="line">            <span class="token class-name"><span class="token keyword">var</span></span> ev <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">WechatsubscribeEvent</span></span>
<span class="line">            <span class="token punctuation">{</span></span>
<span class="line">                OpenId <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"FromUserName"</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">                IsSubscribe <span class="token operator">=</span> eventType <span class="token operator">==</span> <span class="token string">"subscribe"</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token comment">// 将 OpenId 存储在缓存中以便临时登录验证</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span>ev<span class="token punctuation">.</span>IsSubscribe<span class="token punctuation">)</span></span>
<span class="line">            <span class="token punctuation">{</span></span>
<span class="line">                _cacheService<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span><span class="token string">"wechat:openid:"</span> <span class="token operator">+</span> ev<span class="token punctuation">.</span>OpenId<span class="token punctuation">,</span> ev<span class="token punctuation">.</span>OpenId<span class="token punctuation">,</span> <span class="token number">86400</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 存储 24 小时</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> hasEventKey <span class="token operator">=</span> dicData<span class="token punctuation">.</span><span class="token function">TryGetValue</span><span class="token punctuation">(</span><span class="token string">"EventKey"</span><span class="token punctuation">,</span> <span class="token keyword">out</span> <span class="token class-name"><span class="token keyword">object</span></span> oEventKey<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>hasEventKey<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">            <span class="token comment">// 处理 EventKey 逻辑</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">else</span></span>
<span class="line">    <span class="token punctuation">{</span></span>
<span class="line">        <span class="token class-name"><span class="token keyword">var</span></span> v <span class="token operator">=</span> <span class="token punctuation">(</span>ResponseMsgType<span class="token punctuation">)</span>Enum<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token keyword">typeof</span><span class="token punctuation">(</span><span class="token type-expression class-name">ResponseMsgType</span><span class="token punctuation">)</span><span class="token punctuation">,</span> msgType<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">switch</span> <span class="token punctuation">(</span>v<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">case</span> ResponseMsgType<span class="token punctuation">.</span>Empty<span class="token punctuation">:</span></span>
<span class="line">                <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">            <span class="token keyword">case</span> ResponseMsgType<span class="token punctuation">.</span>Text<span class="token punctuation">:</span></span>
<span class="line">                <span class="token class-name"><span class="token keyword">var</span></span> xmlbody <span class="token operator">=</span> Util<span class="token punctuation">.</span><span class="token function">ClearXmlHeader</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span>XmlData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token class-name">MessageBase</span> obj <span class="token operator">=</span> <span class="token punctuation">(</span>MessageBase<span class="token punctuation">)</span>_xmlSerializer<span class="token punctuation">.</span><span class="token function">Deserialize</span><span class="token punctuation">(</span>xmlbody<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">                <span class="token comment">// 获取用户发送的文本内容</span></span>
<span class="line">                <span class="token class-name"><span class="token keyword">var</span></span> userContent <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"Content"</span><span class="token punctuation">]</span><span class="token punctuation">?.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">?.</span><span class="token function">Trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token class-name"><span class="token keyword">var</span></span> fromUserName <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"FromUserName"</span><span class="token punctuation">]</span><span class="token punctuation">?.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token class-name"><span class="token keyword">var</span></span> toUserName <span class="token operator">=</span> dicData<span class="token punctuation">[</span><span class="token string">"ToUserName"</span><span class="token punctuation">]</span><span class="token punctuation">?.</span><span class="token function">ToString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">                <span class="token comment">// 检查用户是否发送了"验证码"</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">string</span><span class="token punctuation">.</span><span class="token function">IsNullOrEmpty</span><span class="token punctuation">(</span>userContent<span class="token punctuation">)</span> <span class="token operator">&amp;&amp;</span> userContent<span class="token punctuation">.</span><span class="token function">Equals</span><span class="token punctuation">(</span><span class="token string">"验证码"</span><span class="token punctuation">,</span> StringComparison<span class="token punctuation">.</span>OrdinalIgnoreCase<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">                <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token comment">// 使用加密安全的随机数生成 6 位验证码</span></span>
<span class="line">                    <span class="token class-name"><span class="token keyword">var</span></span> verificationCode <span class="token operator">=</span> <span class="token function">GenerateSecureVerificationCode</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                    </span>
<span class="line">                    <span class="token comment">// 将验证码与 OpenId 存储</span></span>
<span class="line">                    <span class="token class-name"><span class="token keyword">var</span></span> openId <span class="token operator">=</span> obj<span class="token punctuation">.</span>FromUserName<span class="token punctuation">;</span></span>
<span class="line">                    _cacheService<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span><span class="token string">"code:"</span> <span class="token operator">+</span> verificationCode<span class="token punctuation">,</span> verificationCode<span class="token punctuation">,</span> <span class="token number">180</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                    _cacheService<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span><span class="token string">"openid:"</span> <span class="token operator">+</span> verificationCode<span class="token punctuation">,</span> openId<span class="token punctuation">,</span> <span class="token number">180</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">                    <span class="token comment">// 构造回复消息 XML</span></span>
<span class="line">                    <span class="token class-name"><span class="token keyword">var</span></span> replyXml <span class="token operator">=</span> <span class="token interpolation-string"><span class="token string">$@"&lt;xml></span>
<span class="line">                                        &lt;ToUserName>&lt;![CDATA[</span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">obj<span class="token punctuation">.</span>FromUserName</span><span class="token punctuation">}</span></span><span class="token string">]]>&lt;/ToUserName></span>
<span class="line">                                        &lt;FromUserName>&lt;![CDATA[</span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">obj<span class="token punctuation">.</span>ToUserName</span><span class="token punctuation">}</span></span><span class="token string">]]>&lt;/FromUserName></span>
<span class="line">                                        &lt;CreateTime></span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">DateTimeOffset<span class="token punctuation">.</span>UtcNow<span class="token punctuation">.</span><span class="token function">ToUnixTimeSeconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span><span class="token punctuation">}</span></span><span class="token string">&lt;/CreateTime></span>
<span class="line">                                        &lt;MsgType>&lt;![CDATA[text]]>&lt;/MsgType></span>
<span class="line">                                        &lt;Content>&lt;![CDATA[您的验证码是：</span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">verificationCode</span><span class="token punctuation">}</span></span><span class="token string">，有效期3分钟，请妥善保管。]]>&lt;/Content></span>
<span class="line">                                    &lt;/xml>"</span></span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">                    <span class="token keyword">return</span> replyXml<span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">                <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">default</span><span class="token punctuation">:</span></span>
<span class="line">                <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">await</span> Task<span class="token punctuation">.</span>CompletedTask<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">return</span> <span class="token string">""</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
<h4 id="_5-登录实现" tabindex="-1"><a class="header-anchor" href="#_5-登录实现"><span>5. 登录实现</span></a></h4>
<blockquote>
<p>我们使用 _cacheService 缓存来实现记录用户的openid,来存储判断用户是否已经登录过了.
根据 verificationCode 来判断用户 输入的验证码是否正确
登陆给用户添加默认角色.颁发token
登录逻辑都不同,这里就不展示代码了</p>
</blockquote>
</div></template>


